#define KEY_A        0x04   // Code HID pour "A"
#define KEY_B        0x05   // Code HID pour "B"
#define KEY_C        0x06   // Code HID pour "C"
#define KEY_D        0x07   // Code HID pour "D"
#define KEY_E        0x08   // Code HID pour "E"
#define KEY_F        0x09   // Code HID pour "F"
#define KEY_G        0x0A   // Code HID pour "G"
#define KEY_H        0x0B   // Code HID pour "H"
#define KEY_I        0x0C   // Code HID pour "I"
#define KEY_J        0x0D   // Code HID pour "J"
#define KEY_K        0x0E   // Code HID pour "K"
#define KEY_L        0x0F   // Code HID pour "L"
#define KEY_M        0x10   // Code HID pour "M"
#define KEY_N        0x11   // Code HID pour "N"
#define KEY_O        0x12   // Code HID pour "O"
#define KEY_P        0x13   // Code HID pour "P"
#define KEY_Q        0x14   // Code HID pour "Q"
#define KEY_R        0x15   // Code HID pour "R"
#define KEY_S        0x16   // Code HID pour "S"
#define KEY_T        0x17   // Code HID pour "T"
#define KEY_U        0x18   // Code HID pour "U"
#define KEY_V        0x19   // Code HID pour "V"
#define KEY_W        0x1A   // Code HID pour "W"
#define KEY_X        0x1B   // Code HID pour "X"
#define KEY_Y        0x1C   // Code HID pour "Y"
#define KEY_Z        0x1D   // Code HID pour "Z"

#define KEY_1        0x1E   // Code HID pour "1"
#define KEY_2        0x1F   // Code HID pour "2"
#define KEY_3        0x20   // Code HID pour "3"
#define KEY_4        0x21   // Code HID pour "4"
#define KEY_5        0x22   // Code HID pour "5"
#define KEY_6        0x23   // Code HID pour "6"
#define KEY_7        0x24   // Code HID pour "7"
#define KEY_8        0x25   // Code HID pour "8"
#define KEY_9        0x26   // Code HID pour "9"
#define KEY_0        0x27   // Code HID pour "0"

#define KEY_ENTER    0x28   // Code HID pour "Enter"
#define KEY_ESC      0x29   // Code HID pour "Échap"
#define KEY_BACKSPACE 0x2A  // Code HID pour "Retour arrière"
#define KEY_TAB      0x2B   // Code HID pour "Tabulation"
#define KEY_SPACE    0x2C   // Code HID pour "Espace"

#define KEY_MINUS    0x2D   // Code HID pour "-"
#define KEY_EQUAL    0x2E   // Code HID pour "="
#define KEY_LEFT_BRACE  0x2F  // Code HID pour "["
#define KEY_RIGHT_BRACE 0x30  // Code HID pour "]"
#define KEY_BACKSLASH 0x31   // Code HID pour "\"
#define KEY_SEMICOLON 0x33   // Code HID pour ";"
#define KEY_QUOTE    0x34   // Code HID pour "'"
#define KEY_TILDE    0x35   // Code HID pour "`"
#define KEY_COMMA    0x36   // Code HID pour ","
#define KEY_PERIOD   0x37   // Code HID pour "."
#define KEY_SLASH    0x38   // Code HID pour "/"

#define KEY_CAPS_LOCK  0x39   // Code HID pour "Verr Maj"

#define KEY_F1       0x3A   // Code HID pour "F1"
#define KEY_F2       0x3B   // Code HID pour "F2"
#define KEY_F3       0x3C   // Code HID pour "F3"
#define KEY_F4       0x3D   // Code HID pour "F4"
#define KEY_F5       0x3E   // Code HID pour "F5"
#define KEY_F6       0x3F   // Code HID pour "F6"
#define KEY_F7       0x40   // Code HID pour "F7"
#define KEY_F8       0x41   // Code HID pour "F8"
#define KEY_F9       0x42   // Code HID pour "F9"
#define KEY_F10      0x43   // Code HID pour "F10"
#define KEY_F11      0x44   // Code HID pour "F11"
#define KEY_F12      0x45   // Code HID pour "F12"

#define KEY_PRINTSCREEN 0x46  // Code HID pour "Impr écran"
#define KEY_SCROLL_LOCK 0x47  // Code HID pour "Arrêt défil"
#define KEY_PAUSE     0x48   // Code HID pour "Pause"

#define KEY_INSERT   0x49   // Code HID pour "Insert"
#define KEY_HOME     0x4A   // Code HID pour "Début"
#define KEY_PAGE_UP  0x4B   // Code HID pour "Page Up"
#define KEY_DELETE   0x4C   // Code HID pour "Suppr"
#define KEY_END      0x4D   // Code HID pour "Fin"
#define KEY_PAGE_DOWN 0x4E  // Code HID pour "Page Down"

#define KEY_RIGHT_ARROW  0x4F // Code HID pour "Flèche droite"
#define KEY_LEFT_ARROW   0x50 // Code HID pour "Flèche gauche"
#define KEY_DOWN_ARROW   0x51 // Code HID pour "Flèche bas"
#define KEY_UP_ARROW     0x52 // Code HID pour "Flèche haut"

#define KEY_CTRL      0x01   // Code HID pour "Ctrl"
#define KEY_SHIFT     0x02   // Code HID pour "Shift"
#define KEY_ALT       0x04   // Code HID pour "Alt"
#define KEY_GUI       0x08   // Code HID pour "Win / Cmd"
